import type { Conference, ConferenceId, TeamSeed } from "./types";
import { CAREER_MAX_PRESTIGE } from "./types";

export const CONFERENCES: Conference[] = [
  { id: "AE", name: "North Atlantic", short: "N. Atl.", prestige: 54 },
  { id: "AAC", name: "Gulf Circuit", short: "Gulf", prestige: 64 },
  { id: "ACC", name: "Coastal", short: "Coastal", prestige: 76 },
  { id: "ASUN", name: "Sunshine", short: "Sun", prestige: 52 },
  { id: "A10", name: "Tenfold", short: "Tenfold", prestige: 64 },
  { id: "BE", name: "Eastern", short: "Eastern", prestige: 76 },
  { id: "BSKY", name: "High Country", short: "High Ctry", prestige: 52 },
  { id: "BSOU", name: "Carolina Hills", short: "Hills", prestige: 52 },
  { id: "B10", name: "Great Lakes", short: "Lakes", prestige: 77 },
  { id: "B12", name: "Plains", short: "Plains", prestige: 78 },
  { id: "BW", name: "Pacific West", short: "Pac West", prestige: 56 },
  { id: "CAA", name: "Tidewater", short: "Tidewater", prestige: 56 },
  { id: "CUSA", name: "Mid-South", short: "Mid-South", prestige: 58 },
  { id: "HOR", name: "Lakeshore", short: "Shore", prestige: 54 },
  { id: "IVY", name: "Ancient Eight", short: "Eight", prestige: 58 },
  { id: "MAAC", name: "Metro East", short: "Metro", prestige: 54 },
  { id: "MAC", name: "Heartland", short: "Heartland", prestige: 56 },
  { id: "MEAC", name: "Mid-Atlantic", short: "Mid-Atl", prestige: 48 },
  { id: "MVC", name: "Valley", short: "Valley", prestige: 62 },
  { id: "MW", name: "Mountain", short: "Mountain", prestige: 64 },
  { id: "NEC", name: "Northeast Ridge", short: "Ridge", prestige: 48 },
  { id: "OVC", name: "River", short: "River", prestige: 52 },
  { id: "PAT", name: "Heritage", short: "Heritage", prestige: 52 },
  { id: "P12", name: "Pacific Slope", short: "Slope", prestige: 72 },
  { id: "SEC", name: "Southern", short: "Southern", prestige: 78 },
  { id: "SOC", name: "Appalachian", short: "App", prestige: 56 },
  { id: "SLAND", name: "Bayou", short: "Bayou", prestige: 52 },
  { id: "SWAC", name: "Delta", short: "Delta", prestige: 48 },
  { id: "SUM", name: "Prairie", short: "Prairie", prestige: 54 },
  { id: "SBC", name: "Sun Circuit", short: "Sun Cir", prestige: 58 },
  { id: "UAC", name: "Heartland South", short: "H. South", prestige: 54 },
  { id: "WCC", name: "Pacific Rim", short: "Rim", prestige: 62 },
  { id: "SWC", name: "Southwest", short: "Southwest", prestige: 72 },
  { id: "IND", name: "Independents", short: "Indep.", prestige: 64 },
];

const RAW: [string, string, string, string, ConferenceId, string, string, string][] = [
  ["albany", "Albany", "Drifts", "ALB", "AE", "Albany", "NY", "#46166B"],
  ["binghamton", "Vestal", "Gulfs", "VES", "AE", "Vestal", "NY", "#005A43"],
  ["bryant", "Smithfield", "Stakes", "SMI", "AE", "Smithfield", "RI", "#000000"],
  ["maine", "Orono", "Quills", "ORO", "AE", "Orono", "ME", "#003263"],
  ["umbc", "Catonsville", "Fields", "CAT", "AE", "Baltimore", "MD", "#FDB515"],
  ["umass-lowell", "Lowell", "Spruce", "LOW", "AE", "Lowell", "MA", "#003DA5"],
  ["unh", "Durham North", "Trenches", "DN", "AE", "Durham", "NH", "#003087"],
  ["njit", "University Heights", "Tills", "UH", "AE", "Newark", "NJ", "#D22630"],
  ["vermont", "Burlington", "Cairns", "BUR", "AE", "Burlington", "VT", "#154734"],
  ["charlotte", "Charlotte", "Branches", "CHA", "AAC", "Charlotte", "NC", "#005035"],
  ["ecu", "Uptown Green", "Scarps", "UG", "AAC", "Greenville", "NC", "#592A8A"],
  ["fau", "Boca Raton", "Roosts", "BR", "AAC", "Boca Raton", "FL", "#003366"],
  ["memphis", "Bluff City", "Bluff", "BLF", "AAC", "Memphis", "TN", "#0D2240"],
  ["north-texas", "Denton", "Trestles", "DEN", "AAC", "Denton", "TX", "#00853E"],
  ["rice", "Hermann", "Drifts", "HER", "AAC", "Houston", "TX", "#00205B"],
  ["usf", "Tampa", "Wicks", "TAM", "AAC", "Tampa", "FL", "#006747"],
  ["temple", "Broad Street", "Drifts", "BS", "AAC", "Philadelphia", "PA", "#9D2235"],
  ["uab", "Birmingham", "Inlets", "BIR", "AAC", "Birmingham", "AL", "#1E6B52"],
  ["utsa", "San Antonio", "Thaws", "SA", "AAC", "San Antonio", "TX", "#0C2340"],
  ["tulane", "Uptown", "Canyons", "UPT", "AAC", "New Orleans", "LA", "#006747"],
  ["tulsa", "Tulsa", "Harbors", "TUL", "AAC", "Tulsa", "OK", "#002D72"],
  ["wichita-state", "Wichita", "Marshes", "WIC", "AAC", "Wichita", "KS", "#000000"],
  ["boston-college", "Chestnut Hill", "Falls", "CHL", "ACC", "Chestnut Hill", "MA", "#8C2232"],
  ["cal", "Berkeley", "Grove", "BRK", "ACC", "Berkeley", "CA", "#003262"],
  ["clemson", "Fort Hill", "Hill", "FTH", "ACC", "Clemson", "SC", "#F56600"],
  ["duke", "Durham", "Hillmen", "DUR", "ACC", "Durham", "NC", "#003087"],
  ["fsu", "Cascades", "Spear", "CAS", "ACC", "Tallahassee", "FL", "#782F40"],
  ["georgia-tech", "Midtown", "Gold", "MID", "ACC", "Atlanta", "GA", "#B3A369"],
  ["louisville", "Falls City", "Falls", "FLS", "ACC", "Louisville", "KY", "#AD0000"],
  ["miami", "Coral Gables", "Gale", "CGB", "ACC", "Coral Gables", "FL", "#F47321"],
  ["unc", "Chapel Hill", "Pines", "CHH", "ACC", "Chapel Hill", "NC", "#4B9CD3"],
  ["nc-state", "Raleigh", "Red", "RAL", "ACC", "Raleigh", "NC", "#CC0000"],
  ["notre-dame", "South Bend", "Gold", "SBN", "ACC", "South Bend", "IN", "#0C2340"],
  ["pitt", "Steel City", "Steel", "STL", "ACC", "Pittsburgh", "PA", "#003594"],
  ["smu", "Park Cities", "Park", "PKC", "ACC", "Dallas", "TX", "#C8102E"],
  ["stanford", "The Farm", "Farm", "FRM", "ACC", "Stanford", "CA", "#8C1515"],
  ["syracuse", "Salt City", "Salt", "SLT", "ACC", "Syracuse", "NY", "#F76900"],
  ["virginia", "Grounds", "Grounds", "GRD", "ACC", "Charlottesville", "VA", "#232D4B"],
  ["virginia-tech", "Blacksburg", "Scarps", "BLA", "ACC", "Blacksburg", "VA", "#630031"],
  ["wake-forest", "Winston", "Old Gold", "WIN", "ACC", "Winston-Salem", "NC", "#9E7E38"],
  ["bellarmine", "Newburg", "Marrows", "NEW", "ASUN", "Louisville", "KY", "#8C2232"],
  ["fgcu", "Fort Myers", "Locks", "FM", "ASUN", "Fort Myers", "FL", "#002D72"],
  ["jacksonville", "Arlington FL", "Shoals", "AF", "ASUN", "Jacksonville", "FL", "#00539B"],
  ["lipscomb", "Green Hills", "Docks", "GH", "ASUN", "Nashville", "TN", "#331E54"],
  ["unf", "Northside", "Surges", "NOR", "ASUN", "Jacksonville", "FL", "#002855"],
  ["queens", "Charlotte NC", "Quarries", "CN", "ASUN", "Charlotte", "NC", "#003DA5"],
  ["stetson", "DeLand", "Coasts", "DEL", "ASUN", "DeLand", "FL", "#0C2340"],
  ["west-florida", "Pensacola", "Isthmus", "PEN", "ASUN", "Pensacola", "FL", "#00205B"],
  ["davidson", "Davidson", "Scree", "DAV", "A10", "Davidson", "NC", "#AC1A2F"],
  ["dayton", "Gem City", "Fly", "GEM", "A10", "Dayton", "OH", "#CE1141"],
  ["duquesne", "Pittsburgh PA", "Wharfs", "PP", "A10", "Pittsburgh", "PA", "#041E42"],
  ["fordham", "Rose Hill", "Isthmus", "RH", "A10", "Bronx", "NY", "#860038"],
  ["george-mason", "Fairfax", "Gulfs", "FAI", "A10", "Fairfax", "VA", "#006633"],
  ["george-washington", "Foggy Bottom", "Crosses", "FB", "A10", "Washington", "DC", "#003368"],
  ["lasalle", "Olney", "Hearths", "OLN", "A10", "Philadelphia", "PA", "#003087"],
  ["loyola-chicago", "Rogers Park", "Trestles", "RP", "A10", "Chicago", "IL", "#922247"],
  ["uri", "Kingston", "Chords", "KIN", "A10", "Kingston", "RI", "#002147"],
  ["richmond", "The Fan", "Cedars", "TF", "A10", "Richmond", "VA", "#000066"],
  ["st-bonaventure", "Allegany", "Folds", "ALL", "A10", "St. Bonaventure", "NY", "#79232F"],
  ["saint-josephs", "Overbrook", "Loam", "OVE", "A10", "Philadelphia", "PA", "#9D2235"],
  ["saint-louis", "St. Louis", "Embers", "SL", "A10", "St. Louis", "MO", "#003DA5"],
  ["vcu", "Monroe Park", "Flats", "MP", "A10", "Richmond", "VA", "#000000"],
  ["butler", "Hinkle", "Hinkle", "HNK", "BE", "Indianapolis", "IN", "#13294B"],
  ["creighton", "Omaha West", "Blue", "OMA", "BE", "Omaha", "NE", "#005EB8"],
  ["depaul", "Lincoln Park", "Lake", "LPK", "BE", "Chicago", "IL", "#005EB8"],
  ["georgetown", "The Harbor", "Harbor", "HBR", "BE", "Washington", "DC", "#041E42"],
  ["marquette", "Milwaukee East", "Gold", "MKE", "BE", "Milwaukee", "WI", "#003366"],
  ["providence", "College Hill RI", "Groves", "PVD", "BE", "Providence", "RI", "#000000"],
  ["st-johns", "Queens", "Red", "QNS", "BE", "Queens", "NY", "#BA0C2F"],
  ["seton-hall", "South Orange", "Ash", "SO", "BE", "South Orange", "NJ", "#004488"],
  ["uconn", "Storrs", "Oaks", "STO", "BE", "Storrs", "CT", "#000E2F"],
  ["villanova", "Main Line", "Navy", "MLN", "BE", "Villanova", "PA", "#13B5EA"],
  ["xavier", "Norwood", "Blue", "NORW", "BE", "Cincinnati", "OH", "#002857"],
  ["eastern-washington", "Cheney", "Groves", "CHE", "BSKY", "Cheney", "WA", "#A10022"],
  ["idaho", "Moscow", "Pines", "MOS", "BSKY", "Moscow", "ID", "#B3995D"],
  ["idaho-state", "Pocatello", "Loam", "POC", "BSKY", "Pocatello", "ID", "#F47920"],
  ["montana", "Missoula", "Rifts", "MIS", "BSKY", "Missoula", "MT", "#5E5144"],
  ["montana-state", "Bozeman", "Ponds", "BOZ", "BSKY", "Bozeman", "MT", "#00205B"],
  ["northern-arizona", "Flagstaff", "Ash", "FLA", "BSKY", "Flagstaff", "AZ", "#003466"],
  ["northern-colorado", "Greeley", "Cliffs", "GRE", "BSKY", "Greeley", "CO", "#013C65"],
  ["portland-state", "Park Blocks", "Tills", "PB", "BSKY", "Portland", "OR", "#154734"],
  ["southern-utah", "Cedar City", "Ferns", "CC", "BSKY", "Cedar City", "UT", "#C41230"],
  ["utah-tech", "St. George", "Fathoms", "SG", "BSKY", "St. George", "UT", "#C41230"],
  ["weber-state", "Ogden", "Strands", "OGD", "BSKY", "Ogden", "UT", "#4B2682"],
  ["charleston-southern", "North Charleston", "Gulfs", "NC", "BSOU", "North Charleston", "SC", "#002868"],
  ["gardner-webb", "Boiling Springs", "Knolls", "BOI", "BSOU", "Boiling Springs", "NC", "#C41230"],
  ["high-point", "High Point", "Groves", "HP", "BSOU", "High Point", "NC", "#330072"],
  ["longwood", "Farmville", "Turns", "FAR", "BSOU", "Farmville", "VA", "#0033A0"],
  ["presbyterian", "Clinton", "Wood", "CLI", "BSOU", "Clinton", "SC", "#005EB8"],
  ["radford", "Radford", "Oaks", "RAD", "BSOU", "Radford", "VA", "#C41230"],
  ["unc-asheville", "Asheville", "Keystones", "ASH", "BSOU", "Asheville", "NC", "#003DA5"],
  ["usc-upstate", "Spartanburg East", "Leas", "SE", "BSOU", "Spartanburg", "SC", "#006341"],
  ["winthrop", "Rock Hill", "Reefs", "ROC", "BSOU", "Rock Hill", "SC", "#660000"],
  ["ucla", "Westwood", "Palms", "WWD", "B10", "Los Angeles", "CA", "#2D68C4"],
  ["illinois", "Champaign", "Orange", "CHM", "B10", "Champaign", "IL", "#E84A27"],
  ["indiana", "Bloomington", "Limestone", "BLO", "B10", "Bloomington", "IN", "#990000"],
  ["iowa", "Iowa City", "River", "IC", "B10", "Iowa City", "IA", "#000000"],
  ["maryland", "College Park", "Shell", "CPK", "B10", "College Park", "MD", "#E03A3E"],
  ["michigan", "Ann Arbor", "Maize", "AA", "B10", "Ann Arbor", "MI", "#00274C"],
  ["michigan-state", "East Lansing", "Green", "EL", "B10", "East Lansing", "MI", "#18453B"],
  ["minnesota", "Minneapolis", "North", "MIN", "B10", "Minneapolis", "MN", "#7A0019"],
  ["nebraska", "Lincoln", "Grain", "LNC", "B10", "Lincoln", "NE", "#E41C38"],
  ["northwestern", "Evanston", "Lake", "EVA", "B10", "Evanston", "IL", "#4E2A84"],
  ["ohio-state", "Columbus", "Scarlet", "CLB", "B10", "Columbus", "OH", "#BB0000"],
  ["oregon", "Eugene", "Fir", "EUG", "B10", "Eugene", "OR", "#154733"],
  ["penn-state", "University Park", "Mountain", "UPK", "B10", "University Park", "PA", "#041E42"],
  ["purdue", "West Lafayette", "Rails", "WLA", "B10", "West Lafayette", "IN", "#CEB888"],
  ["rutgers", "Piscataway", "Wind", "PIS", "B10", "Piscataway", "NJ", "#CC0033"],
  ["usc", "Exposition", "Colonnade", "EXP", "B10", "Los Angeles", "CA", "#990000"],
  ["washington", "Montlake", "Sound", "MTK", "B10", "Seattle", "WA", "#4B2E83"],
  ["wisconsin", "Madison", "Crest", "MAD", "B10", "Madison", "WI", "#C5050C"],
  ["arizona", "Tucson", "Desert", "TUC", "B12", "Tucson", "AZ", "#CC0033"],
  ["arizona-state", "Tempe", "Sun", "TEM", "B12", "Tempe", "AZ", "#8C1D40"],
  ["baylor", "Waco", "Green", "WAC", "B12", "Waco", "TX", "#154734"],
  ["byu", "Provo", "Peak", "PRV", "B12", "Provo", "UT", "#002E5D"],
  ["ucf", "Orlando", "Notches", "ORL", "B12", "Orlando", "FL", "#000000"],
  ["cincinnati", "Clifton", "Sluices", "CLF", "B12", "Cincinnati", "OH", "#E00122"],
  ["colorado", "Boulder", "Flatiron", "BLD", "B12", "Boulder", "CO", "#CFB87C"],
  ["houston", "Bayou City", "Steel", "BAY", "B12", "Houston", "TX", "#C8102E"],
  ["iowa-state", "Ames", "Wind", "AME", "B12", "Ames", "IA", "#C8102E"],
  ["kansas", "Lawrence", "Wheat", "LAW", "B12", "Lawrence", "KS", "#0051BA"],
  ["kansas-state", "Manhattan KS", "Prairie", "MHK", "B12", "Manhattan", "KS", "#512888"],
  ["oklahoma-state", "Stillwater", "Coves", "STW", "B12", "Stillwater", "OK", "#FF7300"],
  ["tcu", "Fort Worth", "Violet", "FTW", "B12", "Fort Worth", "TX", "#4D1979"],
  ["texas-tech", "Lubbock", "Dust", "LBB", "B12", "Lubbock", "TX", "#CC0000"],
  ["utah", "Salt Lake", "Spires", "SLC", "B12", "Salt Lake City", "UT", "#CC0000"],
  ["west-virginia", "Morgantown", "Ridge", "MGN", "B12", "Morgantown", "WV", "#002855"],
  ["cal-baptist", "Magnolia", "Wells", "MAG", "BW", "Riverside", "CA", "#002D72"],
  ["cal-poly", "San Luis Obispo", "Brakes", "SLO", "BW", "San Luis Obispo", "CA", "#154734"],
  ["csu-bakersfield", "Bakersfield", "Hearths", "BAK", "BW", "Bakersfield", "CA", "#003DA5"],
  ["csu-fullerton", "Fullerton", "Veils", "FUL", "BW", "Fullerton", "CA", "#00274C"],
  ["csun", "Northridge", "Flats", "NORT", "BW", "Northridge", "CA", "#D22030"],
  ["long-beach-state", "Long Beach", "Brooks", "LB", "BW", "Long Beach", "CA", "#000000"],
  ["sacramento-state", "Sacramento", "Yards", "SAC", "BW", "Sacramento", "CA", "#043927"],
  ["uc-irvine", "Irvine", "Wisps", "IRV", "BW", "Irvine", "CA", "#0C2340"],
  ["uc-riverside", "Box Springs", "Quills", "BOX", "BW", "Riverside", "CA", "#003DA5"],
  ["uc-san-diego", "La Jolla", "Ferns", "LJ", "BW", "La Jolla", "CA", "#182B49"],
  ["uc-santa-barbara", "Santa Barbara", "Rapids", "SB", "BW", "Santa Barbara", "CA", "#003660"],
  ["utah-valley", "Orem", "Orchards", "ORE", "BW", "Orem", "UT", "#275D38"],
  ["campbell", "Buies Creek", "Reefs", "BC", "CAA", "Buies Creek", "NC", "#F57E20"],
  ["charleston", "Harbor City", "Anvils", "HC", "CAA", "Charleston", "SC", "#9B2242"],
  ["drexel", "Powelton", "Gales", "POW", "CAA", "Philadelphia", "PA", "#002D72"],
  ["elon", "Elon", "Salt", "ELO", "CAA", "Elon", "NC", "#73000A"],
  ["hampton", "Hampton", "Plumes", "HAM", "CAA", "Hampton", "VA", "#0067A0"],
  ["hofstra", "Hempstead", "Frost", "HEM", "CAA", "Hempstead", "NY", "#003591"],
  ["monmouth", "West Long Branch", "Peaks", "WLB", "CAA", "West Long Branch", "NJ", "#041E42"],
  ["ncat", "Greensboro East", "Lagoons", "GE", "CAA", "Greensboro", "NC", "#004684"],
  ["northeastern", "Fenway", "Nimbus", "FEN", "CAA", "Boston", "MA", "#D41B2C"],
  ["stony-brook", "Stony Brook", "Chalk", "STON", "CAA", "Stony Brook", "NY", "#990000"],
  ["towson", "Towson", "Inlets", "TOW", "CAA", "Towson", "MD", "#000000"],
  ["uncw", "Wilmington NC", "Chords", "WN", "CAA", "Wilmington", "NC", "#003C71"],
  ["william-mary", "Williamsburg", "Oxbows", "WIL", "CAA", "Williamsburg", "VA", "#115740"],
  ["delaware", "The Green", "Stacks", "TG", "CUSA", "Newark", "DE", "#00539F"],
  ["fiu", "Sweetwater", "Trenches", "SWE", "CUSA", "Miami", "FL", "#081E3F"],
  ["jacksonville-state", "Jacksonville AL", "Hearths", "JA", "CUSA", "Jacksonville", "AL", "#C41230"],
  ["kennesaw-state", "Kennesaw", "Eddies", "KEN", "CUSA", "Kennesaw", "GA", "#000000"],
  ["liberty", "Lynchburg", "Vales", "LYN", "CUSA", "Lynchburg", "VA", "#0A254E"],
  ["middle-tennessee", "Murfreesboro", "Wells", "MUR", "CUSA", "Murfreesboro", "TN", "#0066CC"],
  ["missouri-state", "Springfield", "Flares", "SPR", "CUSA", "Springfield", "MO", "#5E0009"],
  ["new-mexico-state", "Las Cruces", "Strands", "LC", "CUSA", "Las Cruces", "NM", "#8B2332"],
  ["sam-houston", "Huntsville TX", "Harbors", "HT", "CUSA", "Huntsville", "TX", "#F47321"],
  ["wku", "Bowling Green KY", "Fields", "BGK", "CUSA", "Bowling Green", "KY", "#C41230"],
  ["cleveland-state", "Cleveland", "Lifts", "CLE", "HOR", "Cleveland", "OH", "#006633"],
  ["detroit-mercy", "Detroit", "Washes", "DET", "HOR", "Detroit", "MI", "#002D72"],
  ["iu-indy", "Indianapolis IN", "Sidings", "II", "HOR", "Indianapolis", "IN", "#9D2235"],
  ["milwaukee", "Milwaukee West", "Coves", "MW", "HOR", "Milwaukee", "WI", "#000000"],
  ["northern-illinois", "DeKalb", "Strands", "DEK", "HOR", "DeKalb", "IL", "#BA0C2F"],
  ["northern-kentucky", "Highland Heights", "Vistas", "HH", "HOR", "Highland Heights", "KY", "#000000"],
  ["oakland", "Rochester", "Crags", "ROCH", "HOR", "Rochester", "MI", "#000000"],
  ["purdue-fort-wayne", "Fort Wayne", "Canals", "FW", "HOR", "Fort Wayne", "IN", "#000000"],
  ["robert-morris", "Moon Township", "Cedars", "MT", "HOR", "Moon Township", "PA", "#14234B"],
  ["green-bay", "Green Bay", "Capes", "GB", "HOR", "Green Bay", "WI", "#006633"],
  ["wright-state", "Nutter", "Canals", "NUT", "HOR", "Dayton", "OH", "#046A38"],
  ["youngstown-state", "Youngstown", "Groves", "YOU", "HOR", "Youngstown", "OH", "#C41230"],
  ["brown", "Providence RI", "Shafts", "PR", "IVY", "Providence", "RI", "#4E3629"],
  ["columbia", "Morningside", "Quarries", "MOR", "IVY", "New York", "NY", "#B9D9EB"],
  ["cornell", "Ithaca", "Brakes", "ITH", "IVY", "Ithaca", "NY", "#B31B1B"],
  ["dartmouth", "Hanover", "Scarps", "HAN", "IVY", "Hanover", "NH", "#00693E"],
  ["harvard", "Cambridge", "Yard", "CAM", "IVY", "Cambridge", "MA", "#A51C30"],
  ["penn", "University City", "Salt", "UC", "IVY", "Philadelphia", "PA", "#011F5B"],
  ["princeton", "Nassau", "Orange", "NAS", "IVY", "Princeton", "NJ", "#E77500"],
  ["yale", "New Haven", "Blue", "NHV", "IVY", "New Haven", "CT", "#00356B"],
  ["canisius", "Buffalo NY", "Finches", "BN", "MAAC", "Buffalo", "NY", "#0C2340"],
  ["fairfield", "The Sound", "Ferns", "TS", "MAAC", "Fairfield", "CT", "#C8102E"],
  ["iona", "New Rochelle", "Hatches", "NR", "MAAC", "New Rochelle", "NY", "#6F2C3F"],
  ["manhattan", "Riverdale", "Folds", "RIV", "MAAC", "Riverdale", "NY", "#00703C"],
  ["marist", "Poughkeepsie", "Trails", "POU", "MAAC", "Poughkeepsie", "NY", "#C8102E"],
  ["merrimack", "North Andover", "Shelves", "NA", "MAAC", "North Andover", "MA", "#0033A0"],
  ["mount-st-marys", "Emmitsburg", "Bluffs", "EMM", "MAAC", "Emmitsburg", "MD", "#0033A0"],
  ["niagara", "Lewiston", "Trenches", "LEW", "MAAC", "Lewiston", "NY", "#582C83"],
  ["quinnipiac", "Hamden", "Keystones", "HAMD", "MAAC", "Hamden", "CT", "#0B2341"],
  ["rider", "Lawrenceville", "Branches", "LAWR", "MAAC", "Lawrenceville", "NJ", "#A32035"],
  ["sacred-heart", "Park Avenue", "Hedges", "PA", "MAAC", "Fairfield", "CT", "#C8102E"],
  ["saint-peters", "Jersey City", "Ash", "JC", "MAAC", "Jersey City", "NJ", "#003DA5"],
  ["siena", "Loudonville", "Reefs", "LOU", "MAAC", "Loudonville", "NY", "#006747"],
  ["akron", "Akron", "Harbors", "AKR", "MAC", "Akron", "OH", "#041E42"],
  ["ball-state", "Muncie", "Oxbows", "MUN", "MAC", "Muncie", "IN", "#BA0C2F"],
  ["bowling-green", "Bowling Green OH", "Branches", "BGO", "MAC", "Bowling Green", "OH", "#FE5000"],
  ["buffalo", "Buffalo Buffalo", "Mills", "BB", "MAC", "Buffalo", "NY", "#005BBB"],
  ["central-michigan", "Mount Pleasant", "Stone", "MOU", "MAC", "Mount Pleasant", "MI", "#6A0032"],
  ["eastern-michigan", "Ypsilanti", "Fords", "YPS", "MAC", "Ypsilanti", "MI", "#006633"],
  ["kent-state", "Kent", "Drifts", "KENT", "MAC", "Kent", "OH", "#002664"],
  ["umass", "Amherst", "Piers", "AMH", "MAC", "Amherst", "MA", "#881C1C"],
  ["miami-oh", "Oxford OH", "Capes", "OO", "MAC", "Oxford", "OH", "#C3142D"],
  ["ohio", "Athens OH", "Rapids", "AO", "MAC", "Athens", "OH", "#00694E"],
  ["toledo", "Toledo", "Copper", "TOL", "MAC", "Toledo", "OH", "#003E7E"],
  ["western-michigan", "Kalamazoo", "Runes", "KAL", "MAC", "Kalamazoo", "MI", "#6C4023"],
  ["coppin-state", "Coppin Heights", "Wharfs", "CH", "MEAC", "Baltimore", "MD", "#0033A0"],
  ["delaware-state", "Dover", "Fords", "DOV", "MEAC", "Dover", "DE", "#C41230"],
  ["howard", "Shaw", "Dales", "SHA", "MEAC", "Washington", "DC", "#003A63"],
  ["umes", "Princess Anne", "Turns", "PRI", "MEAC", "Princess Anne", "MD", "#8C2232"],
  ["morgan-state", "Coldspring", "Marrows", "COL", "MEAC", "Baltimore", "MD", "#F47920"],
  ["norfolk-state", "Norfolk VA", "Forks", "NV", "MEAC", "Norfolk", "VA", "#007A33"],
  ["nc-central", "Hillside", "Crosses", "HIL", "MEAC", "Durham", "NC", "#8C2232"],
  ["south-carolina-state", "Orangeburg", "Quarries", "ORA", "MEAC", "Orangeburg", "SC", "#8C2232"],
  ["belmont", "Music Row", "Mills", "MR", "MVC", "Nashville", "TN", "#002F6C"],
  ["bradley", "Peoria", "Vales", "PEO", "MVC", "Peoria", "IL", "#A50000"],
  ["drake", "Des Moines", "Mints", "DM", "MVC", "Des Moines", "IA", "#004477"],
  ["evansville", "Evansville IN", "Locks", "EI", "MVC", "Evansville", "IN", "#522398"],
  ["illinois-state", "Normal", "Leas", "NORM", "MVC", "Normal", "IL", "#CE1126"],
  ["indiana-state", "Terre Haute", "Terraces", "TH", "MVC", "Terre Haute", "IN", "#0033A0"],
  ["murray-state", "Murray", "Oxbows", "MURR", "MVC", "Murray", "KY", "#002144"],
  ["northern-iowa", "Cedar Falls", "Crosses", "CF", "MVC", "Cedar Falls", "IA", "#4B116F"],
  ["southern-illinois", "Carbondale", "Branches", "CAR", "MVC", "Carbondale", "IL", "#8C2232"],
  ["uic", "West Loop", "Pitches", "WL", "MVC", "Chicago", "IL", "#D50032"],
  ["valparaiso", "Valparaiso", "Grain", "VAL", "MVC", "Valparaiso", "IN", "#492F24"],
  ["air-force", "The Academy", "Academy", "ACD", "MW", "Colorado Springs", "CO", "#003087"],
  ["grand-canyon", "Phoenix West", "Sidings", "PW", "MW", "Phoenix", "AZ", "#522398"],
  ["hawaii", "Manoa", "Sable", "MAN", "MW", "Honolulu", "HI", "#024731"],
  ["nevada", "Truckee", "Forges", "TRU", "MW", "Reno", "NV", "#003366"],
  ["new-mexico", "Albuquerque", "Flumes", "ALBU", "MW", "Albuquerque", "NM", "#BA0C2F"],
  ["san-jose-state", "San Jose", "Surges", "SJ", "MW", "San Jose", "CA", "#0055A5"],
  ["uc-davis", "Davis", "Salt", "DAVI", "MW", "Davis", "CA", "#022851"],
  ["unlv", "The Strip", "Neon", "STP", "MW", "Las Vegas", "NV", "#B10202"],
  ["utep", "El Paso", "Wood", "EP", "MW", "El Paso", "TX", "#FF8200"],
  ["wyoming", "Laramie", "Mesas", "LAR", "MW", "Laramie", "WY", "#492F24"],
  ["central-connecticut", "New Britain", "Lamps", "NB", "NEC", "New Britain", "CT", "#1E4D2B"],
  ["chicago-state", "Pullman IL", "Wharfs", "PI", "NEC", "Chicago", "IL", "#006747"],
  ["fdu", "Teaneck", "Sidings", "TEA", "NEC", "Teaneck", "NJ", "#0033A0"],
  ["le-moyne", "Syracuse NY", "Canals", "SN", "NEC", "Syracuse", "NY", "#006747"],
  ["liu", "Brooklyn", "Bolts", "BRO", "NEC", "Brooklyn", "NY", "#69B3E7"],
  ["mercyhurst", "Erie", "Ledges", "ERI", "NEC", "Erie", "PA", "#006747"],
  ["new-haven", "West Haven", "Flumes", "WH", "NEC", "West Haven", "CT", "#003DA5"],
  ["stonehill", "Easton Green", "Pines", "EG", "NEC", "Easton", "MA", "#4B116F"],
  ["wagner", "Staten Island", "Faults", "SI", "NEC", "Staten Island", "NY", "#004B2D"],
  ["eastern-illinois", "Charleston IL", "Oxbows", "CI", "OVC", "Charleston", "IL", "#003399"],
  ["lindenwood", "St. Charles", "Keystones", "SC", "OVC", "St. Charles", "MO", "#000000"],
  ["morehead-state", "Morehead", "Palisades", "MORE", "OVC", "Morehead", "KY", "#0033A0"],
  ["semo", "Cape Girardeau", "Sluices", "CG", "OVC", "Cape Girardeau", "MO", "#C41230"],
  ["siue", "Edwardsville", "Shelves", "EDW", "OVC", "Edwardsville", "IL", "#C41230"],
  ["southern-indiana", "Evansville Indiana", "Drifts", "EVAN", "OVC", "Evansville", "IN", "#00205B"],
  ["ut-martin", "Martin", "Lifts", "MAR", "OVC", "Martin", "TN", "#F47321"],
  ["tennessee-state", "North Nashville", "Knolls", "NN", "OVC", "Nashville", "TN", "#003087"],
  ["western-illinois", "Macomb", "Brooks", "MAC", "OVC", "Macomb", "IL", "#663399"],
  ["american", "Tenleytown", "Lanterns", "TEN", "PAT", "Washington", "DC", "#C41230"],
  ["army", "The Point", "Black", "PT", "PAT", "West Point", "NY", "#000000"],
  ["boston-u", "Kenmore", "Jetties", "KENM", "PAT", "Boston", "MA", "#CC0000"],
  ["bucknell", "Lewisburg", "Compass", "LEWI", "PAT", "Lewisburg", "PA", "#003366"],
  ["colgate", "Hamilton", "Leas", "HAMI", "PAT", "Hamilton", "NY", "#821019"],
  ["holy-cross", "Worcester", "Irons", "WOR", "PAT", "Worcester", "MA", "#602D2D"],
  ["lafayette", "College Hill PA", "Peaks", "CHP", "PAT", "Easton", "PA", "#8C1D40"],
  ["lehigh", "Bethlehem", "Orchards", "BET", "PAT", "Bethlehem", "PA", "#502D0E"],
  ["loyola-maryland", "Evergreen", "Thorns", "EVE", "PAT", "Baltimore", "MD", "#006747"],
  ["navy", "Annapolis", "Anchor", "ANN", "PAT", "Annapolis", "MD", "#00205B"],
  ["boise-state", "Boise", "Thickets", "BOIS", "P12", "Boise", "ID", "#0033A0"],
  ["colorado-state", "Fort Collins", "Quarries", "FC", "P12", "Fort Collins", "CO", "#1E4D2B"],
  ["fresno-state", "Fresno", "Cedars", "FRE", "P12", "Fresno", "CA", "#C41230"],
  ["gonzaga", "Spokane", "Spires", "SPK", "P12", "Spokane", "WA", "#041E42"],
  ["oregon-state", "Corvallis", "Surges", "COR", "P12", "Corvallis", "OR", "#D73F09"],
  ["san-diego-state", "Mission Valley", "Mission", "MSV", "P12", "San Diego", "CA", "#A6192E"],
  ["texas-state", "San Marcos", "Glades", "SM", "P12", "San Marcos", "TX", "#501214"],
  ["utah-state", "Logan", "Vales", "LOG", "P12", "Logan", "UT", "#0A3055"],
  ["washington-state", "Pullman", "Pines", "PUL", "P12", "Pullman", "WA", "#981E32"],
  ["alabama", "Tuscaloosa", "Forge", "TUS", "SEC", "Tuscaloosa", "AL", "#9E1B32"],
  ["arkansas", "Fayetteville", "Hill", "FAY", "SEC", "Fayetteville", "AR", "#9D2235"],
  ["auburn", "Plains", "Plainsmen", "PLN", "SEC", "Auburn", "AL", "#0C2340"],
  ["florida", "Gainesville", "Swamp", "GNV", "SEC", "Gainesville", "FL", "#0021A5"],
  ["georgia", "Athens GA", "Hedge", "ATH", "SEC", "Athens", "GA", "#BA0C2F"],
  ["kentucky", "Lexington", "Stallions", "LEX", "SEC", "Lexington", "KY", "#0033A0"],
  ["lsu", "Bayou Rouge", "Violet", "BRG", "SEC", "Baton Rouge", "LA", "#461D7C"],
  ["ole-miss", "Oxford MS", "Grove", "OXF", "SEC", "Oxford", "MS", "#CE1126"],
  ["mississippi-state", "Starkville", "Maroon", "STK", "SEC", "Starkville", "MS", "#5D1725"],
  ["missouri", "Flat Branch", "Column", "FLT", "SEC", "Columbia", "MO", "#F1B82D"],
  ["oklahoma", "Norman", "Crimson", "NRM", "SEC", "Norman", "OK", "#841617"],
  ["south-carolina", "Congaree", "Garnet", "CGR", "SEC", "Columbia", "SC", "#73000A"],
  ["tennessee", "Knoxville", "Embers", "KNX", "SEC", "Knoxville", "TN", "#FF8200"],
  ["texas", "Austin", "Capitol", "AUS", "SEC", "Austin", "TX", "#BF5700"],
  ["texas-am", "Station", "Twelfth", "STA", "SEC", "College Station", "TX", "#500000"],
  ["vanderbilt", "West End", "Anchor", "WEN", "SEC", "Nashville", "TN", "#000000"],
  ["chattanooga", "Chattanooga", "Scarps", "CHAT", "SOC", "Chattanooga", "TN", "#00386B"],
  ["citadel", "The Corps", "Coasts", "TC", "SOC", "Charleston", "SC", "#003087"],
  ["etsu", "Johnson City", "Folds", "JOH", "SOC", "Johnson City", "TN", "#041E42"],
  ["furman", "Poinsett", "Granite", "POI", "SOC", "Greenville", "SC", "#582C83"],
  ["mercer", "Macon", "Cairns", "MACO", "SOC", "Macon", "GA", "#F47321"],
  ["samford", "Homewood", "Thorns", "HOM", "SOC", "Birmingham", "AL", "#C41230"],
  ["tennessee-tech", "Cookeville", "Chords", "COO", "SOC", "Cookeville", "TN", "#5E4B1F"],
  ["unc-greensboro", "Greensboro West", "Wharfs", "GW", "SOC", "Greensboro", "NC", "#0F204C"],
  ["vmi", "Lexington VA", "Vales", "LV", "SOC", "Lexington", "VA", "#C41230"],
  ["western-carolina", "Cullowhee", "Piers", "CUL", "SOC", "Cullowhee", "NC", "#594A25"],
  ["wofford", "Spartanburg West", "Bights", "SW", "SOC", "Spartanburg", "SC", "#000000"],
  ["east-texas-am", "Commerce", "Wells", "COM", "SLAND", "Commerce", "TX", "#003087"],
  ["houston-christian", "Sharpstown", "Sluices", "SHAR", "SLAND", "Houston", "TX", "#003087"],
  ["incarnate-word", "San Antonio TX", "Locks", "SAT", "SLAND", "San Antonio", "TX", "#C41230"],
  ["lamar", "Beaumont", "Surges", "BEA", "SLAND", "Beaumont", "TX", "#C41230"],
  ["new-orleans", "Lakefront", "Terraces", "LAK", "SLAND", "New Orleans", "LA", "#0055A5"],
  ["mcneese", "Lake Charles", "Leas", "LAKE", "SLAND", "Lake Charles", "LA", "#005EB8"],
  ["nicholls", "Thibodaux", "Shores", "THI", "SLAND", "Thibodaux", "LA", "#C41230"],
  ["northwestern-state", "Natchitoches", "Fjords", "NAT", "SLAND", "Natchitoches", "LA", "#4B116F"],
  ["southeastern-louisiana", "Hammond", "Surges", "HAMM", "SLAND", "Hammond", "LA", "#006747"],
  ["sfa", "Nacogdoches", "Knots", "NAC", "SLAND", "Nacogdoches", "TX", "#4B116F"],
  ["am-corpus", "Corpus Christi", "Flats", "CORP", "SLAND", "Corpus Christi", "TX", "#0067A0"],
  ["utrgv", "Edinburg", "Zephyrs", "EDI", "SLAND", "Edinburg", "TX", "#F47321"],
  ["alabama-am", "Huntsville AL", "Fathoms", "HA", "SWAC", "Huntsville", "AL", "#660000"],
  ["alabama-state", "Montgomery", "Flares", "MON", "SWAC", "Montgomery", "AL", "#000000"],
  ["alcorn-state", "Lorman", "Spruce", "LOR", "SWAC", "Lorman", "MS", "#4B116F"],
  ["ark-pine-bluff", "Pine Bluff", "Docks", "PIN", "SWAC", "Pine Bluff", "AR", "#000000"],
  ["bethune-cookman", "Daytona Beach", "Cliffs", "DB", "SWAC", "Daytona Beach", "FL", "#8C2232"],
  ["famu", "Frenchtown", "Reefs", "FREN", "SWAC", "Tallahassee", "FL", "#F47321"],
  ["grambling", "Grambling", "Shelves", "GRA", "SWAC", "Grambling", "LA", "#000000"],
  ["jackson-state", "Jackson", "Canyons", "JAC", "SWAC", "Jackson", "MS", "#002D72"],
  ["mississippi-valley", "Itta Bena", "Hatches", "IB", "SWAC", "Itta Bena", "MS", "#C41230"],
  ["prairie-view", "Prairie View", "Nimbus", "PV", "SWAC", "Prairie View", "TX", "#4B116F"],
  ["southern", "Scotlandville", "Hatches", "SCO", "SWAC", "Baton Rouge", "LA", "#72A800"],
  ["texas-southern", "Third Ward", "Strands", "TW", "SWAC", "Houston", "TX", "#6F263D"],
  ["kansas-city", "Kansas City", "Gales", "KC", "SUM", "Kansas City", "MO", "#005EB8"],
  ["north-dakota", "Grand Forks", "Copper", "GF", "SUM", "Grand Forks", "ND", "#009A44"],
  ["ndsu", "Fargo", "Bights", "FARG", "SUM", "Fargo", "ND", "#0A5640"],
  ["omaha", "Omaha East", "Gulfs", "OE", "SUM", "Omaha", "NE", "#000000"],
  ["oral-roberts", "Tulsa OK", "Flares", "TO", "SUM", "Tulsa", "OK", "#00205B"],
  ["st-thomas", "St. Paul", "Grain", "SP", "SUM", "St. Paul", "MN", "#4B116F"],
  ["south-dakota", "Vermillion", "Grain", "VER", "SUM", "Vermillion", "SD", "#C41230"],
  ["south-dakota-state", "Brookings", "Wicks", "BROO", "SUM", "Brookings", "SD", "#0033A0"],
  ["app-state", "Boone", "Ports", "BOO", "SBC", "Boone", "NC", "#000000"],
  ["arkansas-state", "Jonesboro", "Veils", "JON", "SBC", "Jonesboro", "AR", "#CC092F"],
  ["coastal-carolina", "Conway SC", "Pitches", "CS", "SBC", "Conway", "SC", "#006F71"],
  ["georgia-southern", "Statesboro", "Thorns", "STAT", "SBC", "Statesboro", "GA", "#011E41"],
  ["georgia-state", "Downtown ATL", "Fjords", "DA", "SBC", "Atlanta", "GA", "#0039A6"],
  ["jmu", "Harrisonburg", "Bights", "HAR", "SBC", "Harrisonburg", "VA", "#450084"],
  ["louisiana", "Lafayette", "Wood", "LAF", "SBC", "Lafayette", "LA", "#CE181E"],
  ["ulm", "Monroe", "Benches", "MONR", "SBC", "Monroe", "LA", "#8B2332"],
  ["louisiana-tech", "Ruston", "Mints", "RUS", "SBC", "Ruston", "LA", "#003087"],
  ["marshall", "Huntington", "Coves", "HUN", "SBC", "Huntington", "WV", "#00B140"],
  ["odu", "Hampton Roads", "Washes", "HR", "SBC", "Norfolk", "VA", "#003057"],
  ["south-alabama", "Mobile", "Leas", "MOB", "SBC", "Mobile", "AL", "#00205B"],
  ["southern-miss", "Hattiesburg", "Frost", "HAT", "SBC", "Hattiesburg", "MS", "#000000"],
  ["troy", "Troy", "Marrows", "TRO", "SBC", "Troy", "AL", "#8B2332"],
  ["abilene-christian", "Abilene", "Notches", "ABI", "UAC", "Abilene", "TX", "#4B116F"],
  ["austin-peay", "Clarksville", "Ash", "CLA", "UAC", "Clarksville", "TN", "#C41230"],
  ["central-arkansas", "Conway AR", "Thaws", "CA", "UAC", "Conway", "AR", "#4B116F"],
  ["eastern-kentucky", "Richmond KY", "Plumes", "RK", "UAC", "Richmond", "KY", "#8C2232"],
  ["little-rock", "Little Rock", "Locks", "LR", "UAC", "Little Rock", "AR", "#8C2232"],
  ["north-alabama", "Florence", "Forks", "FLO", "UAC", "Florence", "AL", "#4B116F"],
  ["tarleton", "Stephenville", "Capes", "STE", "UAC", "Stephenville", "TX", "#4B116F"],
  ["ut-arlington", "Arlington", "Washes", "ARL", "UAC", "Arlington", "TX", "#0064B1"],
  ["west-georgia", "Carrollton", "Grain", "CARR", "UAC", "Carrollton", "GA", "#C41230"],
  ["denver", "Capitol Hill CO", "Ledges", "CHC", "WCC", "Denver", "CO", "#8B2332"],
  ["lmu", "Playa", "Canyons", "PLA", "WCC", "Los Angeles", "CA", "#8C2232"],
  ["pacific", "Stockton", "Shelves", "STOC", "WCC", "Stockton", "CA", "#F47321"],
  ["pepperdine", "The Bluff", "Sand", "TB", "WCC", "Malibu", "CA", "#00205B"],
  ["portland", "West Hills", "Heaths", "WES", "WCC", "Portland", "OR", "#4B116F"],
  ["saint-marys", "Moraga", "Moraga", "MORA", "WCC", "Moraga", "CA", "#0033A0"],
  ["san-diego", "Alcala", "Ledges", "ALC", "WCC", "San Diego", "CA", "#003087"],
  ["san-francisco", "The Hill", "Currents", "THE", "WCC", "San Francisco", "CA", "#00543C"],
  ["santa-clara", "Mission", "Basins", "MISS", "WCC", "Santa Clara", "CA", "#8C2232"],
  ["seattle", "Capitol Hill WA", "Brine", "CHW", "WCC", "Seattle", "WA", "#AA0000"],
];

const PRESTIGE: Record<string, number> = {
  "uconn": 98,
  "kansas": 97,
  "duke": 96,
  "gonzaga": 96,
  "houston": 95,
  "michigan": 95,
  "unc": 94,
  "florida": 93,
  "villanova": 92,
  "purdue": 92,
  "virginia": 91,
  "baylor": 91,
  "kentucky": 90,
  "arizona": 90,
  "tennessee": 89,
  "alabama": 89,
  "auburn": 88,
  "michigan-state": 88,
  "ucla": 87,
  "creighton": 86,
  "iowa-state": 86,
  "texas-tech": 85,
  "marquette": 85,
  "illinois": 85,
  "san-diego-state": 85,
  "wisconsin": 84,
  "texas": 84,
  "arkansas": 83,
  "oregon": 82,
  "xavier": 82,
  "saint-marys": 82,
  "byu": 81,
  "st-johns": 81,
  "clemson": 81,
  "dayton": 80,
  "memphis": 80,
  "texas-am": 80,
  "miami": 80,
  "iowa": 79,
  "indiana": 78,
  "ohio-state": 78,
  "vcu": 78,
  "utah-state": 78,
  "maryland": 77,
  "boise-state": 77,
  "fau": 77,
  "new-mexico": 77,
  "lsu": 76,
  "oklahoma": 76,
  "tcu": 76,
  "nevada": 76,
  "nc-state": 76,
  "kansas-state": 76,
  "vanderbilt": 76,
  "cincinnati": 75,
  "west-virginia": 75,
  "missouri": 75,
  "mississippi-state": 75,
  "grand-canyon": 75,
  "louisville": 74,
  "georgia": 74,
  "ole-miss": 74,
  "colorado-state": 74,
  "seton-hall": 74,
  "providence": 74,
  "utah": 74,
  "saint-louis": 73,
  "wake-forest": 73,
  "syracuse": 73,
  "south-carolina": 73,
  "drake": 73,
  "liberty": 73,
  "pitt": 73,
  "usc": 72,
  "vermont": 72,
  "uab": 72,
  "smu": 72,
  "arizona-state": 72,
  "fsu": 72,
  "wichita-state": 71,
  "nebraska": 71,
  "princeton": 71,
  "charleston": 71,
  "high-point": 71,
  "colorado": 71,
  "oklahoma-state": 71,
  "northwestern": 70,
  "washington": 70,
  "notre-dame": 70,
  "butler": 70,
  "yale": 70,
  "uc-irvine": 70,
  "north-texas": 70,
  "penn-state": 70,
  "mcneese": 70,
  "santa-clara": 70,
  "st-bonaventure": 70,
  "ucf": 70,
  "virginia-tech": 70,
  "colgate": 69,
  "minnesota": 69,
  "akron": 69,
  "rutgers": 68,
  "uncw": 68,
  "stanford": 68,
  "loyola-chicago": 68,
  "james-madison": 68,
  "jmu": 68,
  "san-francisco": 68,
  "unlv": 68,
  "richmond": 68,
  "cal": 67,
  "furman": 67,
  "davidson": 67,
  "washington-state": 66,
  "oral-roberts": 66,
  "south-dakota-state": 66,
  "hofstra": 66,
  "george-mason": 66,
  "georgia-tech": 66,
  "georgetown": 65,
  "oregon-state": 64,
  "new-mexico-state": 64,
  "utah-valley": 64,
  "boston-college": 64,
  "uc-san-diego": 63,
  "seattle": 63,
  "fresno-state": 62,
  "wyoming": 62,
  "norfolk-state": 60,
  "hawaii": 60,
  "depaul": 58,
  "howard": 58,
  "texas-state": 58,
  "denver": 58,
  "air-force": 52,
};

function floorPrestige(id: string, conf: ConferenceId): number {
  const override = PRESTIGE[id];
  if (override != null) return override;
  const cp = CONFERENCES.find((c) => c.id === conf)?.prestige ?? 54;
  const n = Array.from(id).reduce((a, ch) => a + ch.charCodeAt(0), 0);
  return Math.max(44, Math.min(80, Math.round(cp * 0.9 + (n % 9) - 2)));
}

export const TEAMS: TeamSeed[] = RAW.map(([id, name, mascot, abbr, conference, city, state, color]) => ({
  id, name, mascot, abbr, conference, city, state, color,
  prestige: floorPrestige(id, conference),
}));

export const TEAM_BY_ID: Record<string, TeamSeed> = Object.fromEntries(TEAMS.map((t) => [t.id, t]));

export type GuestDiv = "D2" | "D3" | "NAIA";

export interface GuestSchool {
  id: string;
  name: string;
  mascot: string;
  abbr: string;
  city: string;
  div: GuestDiv;
  prestige: number;
  color: string;
}

/** Exhibition-only. Not on the Division I board and not a Career or Pick a Team option. */
export const GUESTS: GuestSchool[] = [
  { id: "cup-riverton", name: "Riverton State", mascot: "Rails", abbr: "RIV", city: "Riverton", div: "D2", prestige: 48, color: "#1d4e89" },
  { id: "cup-harbor", name: "Harbor Tech", mascot: "Gulls", abbr: "HBR", city: "Port Haven", div: "D2", prestige: 46, color: "#0f6e6e" },
  { id: "cup-redoak", name: "Red Oak", mascot: "Acorns", abbr: "OAK", city: "Red Oak", div: "D2", prestige: 44, color: "#8c3a2f" },
  { id: "cup-lakeside", name: "Lakeside", mascot: "Loons", abbr: "LAK", city: "Lakeside", div: "D2", prestige: 47, color: "#245c3a" },
  { id: "cup-northline", name: "Northline", mascot: "Signals", abbr: "NLN", city: "Northline", div: "D2", prestige: 45, color: "#3d4c7a" },
  { id: "cup-cinder", name: "Cinder College", mascot: "Sparks", abbr: "CIN", city: "Cinder", div: "D2", prestige: 43, color: "#6b3f1f" },
  { id: "cup-brigid", name: "St. Brigid", mascot: "Bells", abbr: "SBG", city: "Brigid", div: "D3", prestige: 40, color: "#3f2d56" },
  { id: "cup-elm", name: "Elm & Ivy", mascot: "Scholars", abbr: "ELM", city: "Elm", div: "D3", prestige: 39, color: "#1f4d32" },
  { id: "cup-cobb", name: "Cobb College", mascot: "Owls", abbr: "COB", city: "Cobb", div: "D3", prestige: 38, color: "#5a3e1b" },
  { id: "cup-marlowe", name: "Marlowe", mascot: "Quills", abbr: "MAR", city: "Marlowe", div: "D3", prestige: 41, color: "#6e2b3c" },
  { id: "cup-whitewater", name: "Whitewater College", mascot: "Rapids", abbr: "WWT", city: "Whitewater", div: "D3", prestige: 37, color: "#1c4f73" },
  { id: "cup-pine", name: "Pine Hill", mascot: "Pines", abbr: "PNE", city: "Pine Hill", div: "D3", prestige: 36, color: "#2d4a2a" },
  { id: "cup-wagoner", name: "Wagoner", mascot: "Trail", abbr: "WAG", city: "Wagoner", div: "NAIA", prestige: 42, color: "#7a4b12" },
  { id: "cup-mesa", name: "Mesa Baptist", mascot: "Chapels", abbr: "MES", city: "Mesa", div: "NAIA", prestige: 40, color: "#184e4e" },
  { id: "cup-iron", name: "Iron Range", mascot: "Miners", abbr: "IRN", city: "Iron Range", div: "NAIA", prestige: 39, color: "#4a4036" },
  { id: "cup-keystone", name: "Keystone", mascot: "Arches", abbr: "KEY", city: "Keystone", div: "NAIA", prestige: 41, color: "#2a3d66" },
  { id: "cup-drift", name: "Driftwood", mascot: "Currents", abbr: "DRF", city: "Driftwood", div: "NAIA", prestige: 38, color: "#3e5c4a" },
  { id: "cup-sunbelt", name: "Sunbelt Christian", mascot: "Suns", abbr: "SBCU", city: "Sunbelt", div: "NAIA", prestige: 37, color: "#8a5a12" },
];

export function guestOf(id: string): GuestSchool | undefined {
  return GUESTS.find((g) => g.id === id);
}

export function teamOf(id: string): TeamSeed {
  const t = TEAM_BY_ID[id];
  if (t) return t;
  const g = guestOf(id);
  if (g) {
    return {
      id: g.id,
      name: g.name,
      mascot: g.mascot,
      abbr: g.abbr,
      conference: "IND",
      city: g.city,
      state: g.div,
      color: g.color,
      prestige: g.prestige,
    };
  }
  const clean = (id || "unknown").replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  const abbr = (id || "unk").replace(/[^a-z]/gi, "").slice(0, 3).toUpperCase() || "UNK";
  return {
    id: id || "unknown",
    name: clean || "Unknown",
    mascot: "Club",
    abbr,
    conference: "SEC",
    city: "Campus",
    state: "—",
    color: "#6b6b6b",
    prestige: 50,
  };
}

export { CAREER_MAX_PRESTIGE };
export function careerEligible(t: { prestige: number }) {
  return t.prestige <= CAREER_MAX_PRESTIGE;
}

export function inkOn(hex: string): string {
  const n = (hex || "#6b6b6b").replace("#", "");
  const v = n.length === 3 ? n.split("").map((c) => c + c).join("") : n.padEnd(6, "0").slice(0, 6);
  const r = parseInt(v.slice(0, 2), 16) || 0;
  const g = parseInt(v.slice(2, 4), 16) || 0;
  const b = parseInt(v.slice(4, 6), 16) || 0;
  const lum = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
  return lum > 0.58 ? "#0b0b0c" : "#f2f1ec";
}
