#!/usr/bin/env python3
"""Emit public/packs/real-schools.json from original display names (ids stay)."""
from __future__ import annotations
import json
from pathlib import Path

TEAMS = {
    "albany": ("Albany", "Great Danes", "ALB"),
    "binghamton": ("Binghamton", "Bearcats", "BING"),
    "bryant": ("Bryant", "Bulldogs", "BRY"),
    "maine": ("Maine", "Black Bears", "ME"),
    "umbc": ("UMBC", "Retrievers", "UMBC"),
    "umass-lowell": ("UMass Lowell", "River Hawks", "UML"),
    "unh": ("New Hampshire", "Wildcats", "UNH"),
    "njit": ("NJIT", "Highlanders", "NJIT"),
    "vermont": ("Vermont", "Catamounts", "UVM"),
    "charlotte": ("Charlotte", "49ers", "CLT"),
    "ecu": ("East Carolina", "Pirates", "ECU"),
    "fau": ("Florida Atlantic", "Owls", "FAU"),
    "memphis": ("Memphis", "Tigers", "MEM"),
    "north-texas": ("North Texas", "Mean Green", "UNT"),
    "rice": ("Rice", "Owls", "RICE"),
    "usf": ("South Florida", "Bulls", "USF"),
    "temple": ("Temple", "Owls", "TEM"),
    "uab": ("UAB", "Blazers", "UAB"),
    "utsa": ("UTSA", "Roadrunners", "UTSA"),
    "tulane": ("Tulane", "Green Wave", "TULN"),
    "tulsa": ("Tulsa", "Golden Hurricane", "TLSA"),
    "wichita-state": ("Wichita State", "Shockers", "WICH"),
    "boston-college": ("Boston College", "Eagles", "BC"),
    "cal": ("California", "Golden Bears", "CAL"),
    "clemson": ("Clemson", "Tigers", "CLEM"),
    "duke": ("Duke", "Blue Devils", "DUKE"),
    "fsu": ("Florida State", "Seminoles", "FSU"),
    "georgia-tech": ("Georgia Tech", "Yellow Jackets", "GT"),
    "louisville": ("Louisville", "Cardinals", "LOU"),
    "miami": ("Miami", "Hurricanes", "MIA"),
    "unc": ("North Carolina", "Tar Heels", "UNC"),
    "nc-state": ("NC State", "Wolfpack", "NCST"),
    "notre-dame": ("Notre Dame", "Fighting Irish", "ND"),
    "pitt": ("Pittsburgh", "Panthers", "PITT"),
    "smu": ("SMU", "Mustangs", "SMU"),
    "stanford": ("Stanford", "Cardinal", "STAN"),
    "syracuse": ("Syracuse", "Orange", "SYR"),
    "virginia": ("Virginia", "Cavaliers", "UVA"),
    "virginia-tech": ("Virginia Tech", "Hokies", "VT"),
    "wake-forest": ("Wake Forest", "Demon Deacons", "WAKE"),
    "bellarmine": ("Bellarmine", "Knights", "BELL"),
    "fgcu": ("FGCU", "Eagles", "FGCU"),
    "jacksonville": ("Jacksonville", "Dolphins", "JAC"),
    "lipscomb": ("Lipscomb", "Bisons", "LIP"),
    "unf": ("North Florida", "Ospreys", "UNF"),
    "queens": ("Queens", "Royals", "QUC"),
    "stetson": ("Stetson", "Hatters", "STET"),
    "west-florida": ("West Florida", "Argonauts", "UWF"),
    "davidson": ("Davidson", "Wildcats", "DAV"),
    "dayton": ("Dayton", "Flyers", "DAY"),
    "duquesne": ("Duquesne", "Dukes", "DUQ"),
    "fordham": ("Fordham", "Rams", "FOR"),
    "george-mason": ("George Mason", "Patriots", "GMU"),
    "george-washington": ("George Washington", "Revolutionaries", "GW"),
    "lasalle": ("La Salle", "Explorers", "LAS"),
    "loyola-chicago": ("Loyola Chicago", "Ramblers", "L-IL"),
    "uri": ("Rhode Island", "Rams", "URI"),
    "richmond": ("Richmond", "Spiders", "RICH"),
    "st-bonaventure": ("St. Bonaventure", "Bonnies", "SBON"),
    "saint-josephs": ("Saint Joseph's", "Hawks", "JOES"),
    "saint-louis": ("Saint Louis", "Billikens", "SLU"),
    "vcu": ("VCU", "Rams", "VCU"),
    "butler": ("Butler", "Bulldogs", "BUT"),
    "creighton": ("Creighton", "Bluejays", "CREI"),
    "depaul": ("DePaul", "Blue Demons", "DEP"),
    "georgetown": ("Georgetown", "Hoyas", "GTWN"),
    "marquette": ("Marquette", "Golden Eagles", "MARQ"),
    "providence": ("Providence", "Friars", "PROV"),
    "st-johns": ("St. John's", "Red Storm", "SJU"),
    "seton-hall": ("Seton Hall", "Pirates", "HALL"),
    "uconn": ("UConn", "Huskies", "CONN"),
    "villanova": ("Villanova", "Wildcats", "VILL"),
    "xavier": ("Xavier", "Musketeers", "XAV"),
    "eastern-washington": ("Eastern Washington", "Eagles", "EWU"),
    "idaho": ("Idaho", "Vandals", "IDHO"),
    "idaho-state": ("Idaho State", "Bengals", "IDST"),
    "montana": ("Montana", "Grizzlies", "MONT"),
    "montana-state": ("Montana State", "Bobcats", "MTST"),
    "northern-arizona": ("Northern Arizona", "Lumberjacks", "NAU"),
    "northern-colorado": ("Northern Colorado", "Bears", "UNCO"),
    "portland-state": ("Portland State", "Vikings", "PRST"),
    "southern-utah": ("Southern Utah", "Thunderbirds", "SUU"),
    "utah-tech": ("Utah Tech", "Trailblazers", "UTU"),
    "weber-state": ("Weber State", "Wildcats", "WEB"),
    "charleston-southern": ("Charleston Southern", "Buccaneers", "CHSO"),
    "gardner-webb": ("Gardner-Webb", "Runnin' Bulldogs", "GWEB"),
    "high-point": ("High Point", "Panthers", "HPU"),
    "longwood": ("Longwood", "Lancers", "LONG"),
    "presbyterian": ("Presbyterian", "Blue Hose", "PRE"),
    "radford": ("Radford", "Highlanders", "RAD"),
    "unc-asheville": ("UNC Asheville", "Bulldogs", "UNCA"),
    "usc-upstate": ("USC Upstate", "Spartans", "UPST"),
    "winthrop": ("Winthrop", "Eagles", "WIN"),
    "ucla": ("UCLA", "Bruins", "UCLA"),
    "illinois": ("Illinois", "Fighting Illini", "ILL"),
    "indiana": ("Indiana", "Hoosiers", "IND"),
    "iowa": ("Iowa", "Hawkeyes", "IOWA"),
    "maryland": ("Maryland", "Terrapins", "MD"),
    "michigan": ("Michigan", "Wolverines", "MICH"),
    "michigan-state": ("Michigan State", "Spartans", "MSU"),
    "minnesota": ("Minnesota", "Golden Gophers", "MINN"),
    "nebraska": ("Nebraska", "Cornhuskers", "NEB"),
    "northwestern": ("Northwestern", "Wildcats", "NW"),
    "ohio-state": ("Ohio State", "Buckeyes", "OSU"),
    "oregon": ("Oregon", "Ducks", "ORE"),
    "penn-state": ("Penn State", "Nittany Lions", "PSU"),
    "purdue": ("Purdue", "Boilermakers", "PUR"),
    "rutgers": ("Rutgers", "Scarlet Knights", "RUTG"),
    "usc": ("USC", "Trojans", "USC"),
    "washington": ("Washington", "Huskies", "WASH"),
    "wisconsin": ("Wisconsin", "Badgers", "WIS"),
    "arizona": ("Arizona", "Wildcats", "ARIZ"),
    "arizona-state": ("Arizona State", "Sun Devils", "ASU"),
    "baylor": ("Baylor", "Bears", "BAY"),
    "byu": ("BYU", "Cougars", "BYU"),
    "ucf": ("UCF", "Knights", "UCF"),
    "cincinnati": ("Cincinnati", "Bearcats", "CIN"),
    "colorado": ("Colorado", "Buffaloes", "COLO"),
    "houston": ("Houston", "Cougars", "HOU"),
    "iowa-state": ("Iowa State", "Cyclones", "ISU"),
    "kansas": ("Kansas", "Jayhawks", "KU"),
    "kansas-state": ("Kansas State", "Wildcats", "KSU"),
    "oklahoma-state": ("Oklahoma State", "Cowboys", "OKST"),
    "tcu": ("TCU", "Horned Frogs", "TCU"),
    "texas-tech": ("Texas Tech", "Red Raiders", "TTU"),
    "utah": ("Utah", "Utes", "UTAH"),
    "west-virginia": ("West Virginia", "Mountaineers", "WVU"),
    "cal-baptist": ("Cal Baptist", "Lancers", "CBU"),
    "cal-poly": ("Cal Poly", "Mustangs", "CP"),
    "csu-bakersfield": ("CSU Bakersfield", "Roadrunners", "CSUB"),
    "csu-fullerton": ("CSU Fullerton", "Titans", "CSUF"),
    "csun": ("CSUN", "Matadors", "CSUN"),
    "long-beach-state": ("Long Beach State", "The Beach", "LBSU"),
    "sacramento-state": ("Sacramento State", "Hornets", "SAC"),
    "uc-irvine": ("UC Irvine", "Anteaters", "UCI"),
    "uc-riverside": ("UC Riverside", "Highlanders", "UCR"),
    "uc-san-diego": ("UC San Diego", "Tritons", "UCSD"),
    "uc-santa-barbara": ("UC Santa Barbara", "Gauchos", "UCSB"),
    "utah-valley": ("Utah Valley", "Wolverines", "UVU"),
    "campbell": ("Campbell", "Fighting Camels", "CAM"),
    "charleston": ("Charleston", "Cougars", "COFC"),
    "drexel": ("Drexel", "Dragons", "DREX"),
    "elon": ("Elon", "Phoenix", "ELON"),
    "hampton": ("Hampton", "Pirates", "HAMP"),
    "hofstra": ("Hofstra", "Pride", "HOF"),
    "monmouth": ("Monmouth", "Hawks", "MONM"),
    "ncat": ("NC A&T", "Aggies", "NCAT"),
    "northeastern": ("Northeastern", "Huskies", "NE"),
    "stony-brook": ("Stony Brook", "Seawolves", "SBU"),
    "towson": ("Towson", "Tigers", "TOW"),
    "uncw": ("UNC Wilmington", "Seahawks", "UNCW"),
    "william-mary": ("William & Mary", "Tribe", "W&M"),
    "delaware": ("Delaware", "Fightin' Blue Hens", "DEL"),
    "fiu": ("FIU", "Panthers", "FIU"),
    "jacksonville-state": ("Jacksonville State", "Gamecocks", "JVST"),
    "kennesaw-state": ("Kennesaw State", "Owls", "KENN"),
    "liberty": ("Liberty", "Flames", "LIB"),
    "middle-tennessee": ("Middle Tennessee", "Blue Raiders", "MTSU"),
    "missouri-state": ("Missouri State", "Bears", "MOST"),
    "new-mexico-state": ("New Mexico State", "Aggies", "NMSU"),
    "sam-houston": ("Sam Houston", "Bearkats", "SHSU"),
    "wku": ("Western Kentucky", "Hilltoppers", "WKU"),
    "cleveland-state": ("Cleveland State", "Vikings", "CLEV"),
    "detroit-mercy": ("Detroit Mercy", "Titans", "DETM"),
    "iu-indy": ("IU Indianapolis", "Jaguars", "IUIN"),
    "milwaukee": ("Milwaukee", "Panthers", "MILW"),
    "northern-illinois": ("Northern Illinois", "Huskies", "NIU"),
    "northern-kentucky": ("Northern Kentucky", "Norse", "NKU"),
    "oakland": ("Oakland", "Golden Grizzlies", "OAK"),
    "purdue-fort-wayne": ("Purdue Fort Wayne", "Mastodons", "PFW"),
    "robert-morris": ("Robert Morris", "Colonials", "RMU"),
    "green-bay": ("Green Bay", "Phoenix", "GB"),
    "wright-state": ("Wright State", "Raiders", "WRST"),
    "youngstown-state": ("Youngstown State", "Penguins", "YSU"),
    "brown": ("Brown", "Bears", "BRWN"),
    "columbia": ("Columbia", "Lions", "COLU"),
    "cornell": ("Cornell", "Big Red", "COR"),
    "dartmouth": ("Dartmouth", "Big Green", "DART"),
    "harvard": ("Harvard", "Crimson", "HARV"),
    "penn": ("Penn", "Quakers", "PENN"),
    "princeton": ("Princeton", "Tigers", "PRIN"),
    "yale": ("Yale", "Bulldogs", "YALE"),
    "canisius": ("Canisius", "Golden Griffins", "CAN"),
    "fairfield": ("Fairfield", "Stags", "FFD"),
    "iona": ("Iona", "Gaels", "IONA"),
    "manhattan": ("Manhattan", "Jaspers", "MAN"),
    "marist": ("Marist", "Red Foxes", "MRST"),
    "merrimack": ("Merrimack", "Warriors", "MRMK"),
    "mount-st-marys": ("Mount St. Mary's", "Mountaineers", "MSM"),
    "niagara": ("Niagara", "Purple Eagles", "NIA"),
    "quinnipiac": ("Quinnipiac", "Bobcats", "QUIN"),
    "rider": ("Rider", "Broncs", "RID"),
    "sacred-heart": ("Sacred Heart", "Pioneers", "SHU"),
    "saint-peters": ("Saint Peter's", "Peacocks", "SPU"),
    "siena": ("Siena", "Saints", "SIE"),
    "akron": ("Akron", "Zips", "AKR"),
    "ball-state": ("Ball State", "Cardinals", "BALL"),
    "bowling-green": ("Bowling Green", "Falcons", "BGSU"),
    "buffalo": ("Buffalo", "Bulls", "BUFF"),
    "central-michigan": ("Central Michigan", "Chippewas", "CMU"),
    "eastern-michigan": ("Eastern Michigan", "Eagles", "EMU"),
    "kent-state": ("Kent State", "Golden Flashes", "KENT"),
    "umass": ("UMass", "Minutemen", "MASS"),
    "miami-oh": ("Miami (OH)", "RedHawks", "M-OH"),
    "ohio": ("Ohio", "Bobcats", "OHIO"),
    "toledo": ("Toledo", "Rockets", "TOL"),
    "western-michigan": ("Western Michigan", "Broncos", "WMU"),
    "coppin-state": ("Coppin State", "Eagles", "COPP"),
    "delaware-state": ("Delaware State", "Hornets", "DSU"),
    "howard": ("Howard", "Bison", "HOW"),
    "umes": ("Maryland Eastern Shore", "Hawks", "UMES"),
    "morgan-state": ("Morgan State", "Bears", "MSU-M"),
    "norfolk-state": ("Norfolk State", "Spartans", "NORF"),
    "nc-central": ("NC Central", "Eagles", "NCCU"),
    "south-carolina-state": ("South Carolina State", "Bulldogs", "SCST"),
    "belmont": ("Belmont", "Bruins", "BEL"),
    "bradley": ("Bradley", "Braves", "BRAD"),
    "drake": ("Drake", "Bulldogs", "DRKE"),
    "evansville": ("Evansville", "Purple Aces", "EVAN"),
    "illinois-state": ("Illinois State", "Redbirds", "ILST"),
    "indiana-state": ("Indiana State", "Sycamores", "INST"),
    "murray-state": ("Murray State", "Racers", "MUR"),
    "northern-iowa": ("Northern Iowa", "Panthers", "UNI"),
    "southern-illinois": ("Southern Illinois", "Salukis", "SIU"),
    "uic": ("UIC", "Flames", "UIC"),
    "valparaiso": ("Valparaiso", "Beacons", "VALP"),
    "air-force": ("Air Force", "Falcons", "AFA"),
    "grand-canyon": ("Grand Canyon", "Antelopes", "GCU"),
    "hawaii": ("Hawai'i", "Rainbow Warriors", "HAW"),
    "nevada": ("Nevada", "Wolf Pack", "NEV"),
    "new-mexico": ("New Mexico", "Lobos", "UNM"),
    "san-jose-state": ("San Jose State", "Spartans", "SJSU"),
    "uc-davis": ("UC Davis", "Aggies", "UCD"),
    "unlv": ("UNLV", "Rebels", "UNLV"),
    "utep": ("UTEP", "Miners", "UTEP"),
    "wyoming": ("Wyoming", "Cowboys", "WYO"),
    "central-connecticut": ("Central Connecticut", "Blue Devils", "CCSU"),
    "chicago-state": ("Chicago State", "Cougars", "CHST"),
    "fdu": ("Fairleigh Dickinson", "Knights", "FDU"),
    "le-moyne": ("Le Moyne", "Dolphins", "LEM"),
    "liu": ("LIU", "Sharks", "LIU"),
    "mercyhurst": ("Mercyhurst", "Lakers", "MERC"),
    "new-haven": ("New Haven", "Chargers", "NHV"),
    "stonehill": ("Stonehill", "Skyhawks", "STO"),
    "wagner": ("Wagner", "Seahawks", "WAG"),
    "eastern-illinois": ("Eastern Illinois", "Panthers", "EIU"),
    "lindenwood": ("Lindenwood", "Lions", "LIN"),
    "morehead-state": ("Morehead State", "Eagles", "MORE"),
    "semo": ("Southeast Missouri", "Redhawks", "SEMO"),
    "siue": ("SIU Edwardsville", "Cougars", "SIUE"),
    "southern-indiana": ("Southern Indiana", "Screaming Eagles", "USI"),
    "ut-martin": ("UT Martin", "Skyhawks", "UTM"),
    "tennessee-state": ("Tennessee State", "Tigers", "TNST"),
    "western-illinois": ("Western Illinois", "Leathernecks", "WIU"),
    "american": ("American", "Eagles", "AMER"),
    "army": ("Army", "Black Knights", "ARMY"),
    "boston-u": ("Boston University", "Terriers", "BU"),
    "bucknell": ("Bucknell", "Bison", "BUCK"),
    "colgate": ("Colgate", "Raiders", "COLG"),
    "holy-cross": ("Holy Cross", "Crusaders", "HC"),
    "lafayette": ("Lafayette", "Leopards", "LAF"),
    "lehigh": ("Lehigh", "Mountain Hawks", "LEH"),
    "loyola-maryland": ("Loyola Maryland", "Greyhounds", "L-MD"),
    "navy": ("Navy", "Midshipmen", "NAVY"),
    "boise-state": ("Boise State", "Broncos", "BOIS"),
    "colorado-state": ("Colorado State", "Rams", "CSU"),
    "fresno-state": ("Fresno State", "Bulldogs", "FRES"),
    "gonzaga": ("Gonzaga", "Bulldogs", "GONZ"),
    "oregon-state": ("Oregon State", "Beavers", "ORST"),
    "san-diego-state": ("San Diego State", "Aztecs", "SDSU"),
    "texas-state": ("Texas State", "Bobcats", "TXST"),
    "utah-state": ("Utah State", "Aggies", "USU"),
    "washington-state": ("Washington State", "Cougars", "WSU"),
    "alabama": ("Alabama", "Crimson Tide", "ALA"),
    "arkansas": ("Arkansas", "Razorbacks", "ARK"),
    "auburn": ("Auburn", "Tigers", "AUB"),
    "florida": ("Florida", "Gators", "FLA"),
    "georgia": ("Georgia", "Bulldogs", "UGA"),
    "kentucky": ("Kentucky", "Wildcats", "UK"),
    "lsu": ("LSU", "Tigers", "LSU"),
    "ole-miss": ("Ole Miss", "Rebels", "MISS"),
    "mississippi-state": ("Mississippi State", "Bulldogs", "MSST"),
    "missouri": ("Missouri", "Tigers", "MIZ"),
    "oklahoma": ("Oklahoma", "Sooners", "OU"),
    "south-carolina": ("South Carolina", "Gamecocks", "SCAR"),
    "tennessee": ("Tennessee", "Volunteers", "TENN"),
    "texas": ("Texas", "Longhorns", "TEX"),
    "texas-am": ("Texas A&M", "Aggies", "TA&M"),
    "vanderbilt": ("Vanderbilt", "Commodores", "VAN"),
    "chattanooga": ("Chattanooga", "Mocs", "UTC"),
    "citadel": ("The Citadel", "Bulldogs", "CIT"),
    "etsu": ("East Tennessee State", "Buccaneers", "ETSU"),
    "furman": ("Furman", "Paladins", "FUR"),
    "mercer": ("Mercer", "Bears", "MER"),
    "samford": ("Samford", "Bulldogs", "SAM"),
    "tennessee-tech": ("Tennessee Tech", "Golden Eagles", "TNTC"),
    "unc-greensboro": ("UNC Greensboro", "Spartans", "UNCG"),
    "vmi": ("VMI", "Keydets", "VMI"),
    "western-carolina": ("Western Carolina", "Catamounts", "WCU"),
    "wofford": ("Wofford", "Terriers", "WOF"),
    "east-texas-am": ("East Texas A&M", "Lions", "ETAM"),
    "houston-christian": ("Houston Christian", "Huskies", "HCU"),
    "incarnate-word": ("Incarnate Word", "Cardinals", "UIW"),
    "lamar": ("Lamar", "Cardinals", "LAM"),
    "new-orleans": ("New Orleans", "Privateers", "UNO"),
    "mcneese": ("McNeese", "Cowboys", "MCN"),
    "nicholls": ("Nicholls", "Colonels", "NICH"),
    "northwestern-state": ("Northwestern State", "Demons", "NWST"),
    "southeastern-louisiana": ("Southeastern Louisiana", "Lions", "SELA"),
    "sfa": ("Stephen F. Austin", "Lumberjacks", "SFA"),
    "am-corpus": ("Texas A&M-Corpus Christi", "Islanders", "AMCC"),
    "utrgv": ("UT Rio Grande Valley", "Vaqueros", "UTRGV"),
    "alabama-am": ("Alabama A&M", "Bulldogs", "AAMU"),
    "alabama-state": ("Alabama State", "Hornets", "ALST"),
    "alcorn-state": ("Alcorn State", "Braves", "ALCN"),
    "ark-pine-bluff": ("Arkansas-Pine Bluff", "Golden Lions", "UAPB"),
    "bethune-cookman": ("Bethune-Cookman", "Wildcats", "BCU"),
    "famu": ("Florida A&M", "Rattlers", "FAMU"),
    "grambling": ("Grambling", "Tigers", "GRAM"),
    "jackson-state": ("Jackson State", "Tigers", "JKST"),
    "mississippi-valley": ("Mississippi Valley State", "Delta Devils", "MVSU"),
    "prairie-view": ("Prairie View A&M", "Panthers", "PV"),
    "southern": ("Southern", "Jaguars", "SOU"),
    "texas-southern": ("Texas Southern", "Tigers", "TXSO"),
    "kansas-city": ("Kansas City", "Roos", "KC"),
    "north-dakota": ("North Dakota", "Fighting Hawks", "UND"),
    "ndsu": ("North Dakota State", "Bison", "NDSU"),
    "omaha": ("Omaha", "Mavericks", "OMA"),
    "oral-roberts": ("Oral Roberts", "Golden Eagles", "ORU"),
    "st-thomas": ("St. Thomas", "Tommies", "UST"),
    "south-dakota": ("South Dakota", "Coyotes", "SDAK"),
    "south-dakota-state": ("South Dakota State", "Jackrabbits", "SDST"),
    "app-state": ("Appalachian State", "Mountaineers", "APP"),
    "arkansas-state": ("Arkansas State", "Red Wolves", "ARST"),
    "coastal-carolina": ("Coastal Carolina", "Chanticleers", "CCU"),
    "georgia-southern": ("Georgia Southern", "Eagles", "GASO"),
    "georgia-state": ("Georgia State", "Panthers", "GAST"),
    "jmu": ("James Madison", "Dukes", "JMU"),
    "louisiana": ("Louisiana", "Ragin' Cajuns", "ULL"),
    "ulm": ("UL Monroe", "Warhawks", "ULM"),
    "louisiana-tech": ("Louisiana Tech", "Bulldogs", "LT"),
    "marshall": ("Marshall", "Thundering Herd", "MRSH"),
    "odu": ("Old Dominion", "Monarchs", "ODU"),
    "south-alabama": ("South Alabama", "Jaguars", "USA"),
    "southern-miss": ("Southern Miss", "Golden Eagles", "USM"),
    "troy": ("Troy", "Trojans", "TROY"),
    "abilene-christian": ("Abilene Christian", "Wildcats", "ACU"),
    "austin-peay": ("Austin Peay", "Governors", "PEAY"),
    "central-arkansas": ("Central Arkansas", "Bears", "UCA"),
    "eastern-kentucky": ("Eastern Kentucky", "Colonels", "EKU"),
    "little-rock": ("Little Rock", "Trojans", "UALR"),
    "north-alabama": ("North Alabama", "Lions", "UNA"),
    "tarleton": ("Tarleton", "Texans", "TAR"),
    "ut-arlington": ("UT Arlington", "Mavericks", "UTA"),
    "west-georgia": ("West Georgia", "Wolves", "UWG"),
    "denver": ("Denver", "Pioneers", "DEN"),
    "lmu": ("Loyola Marymount", "Lions", "LMU"),
    "pacific": ("Pacific", "Tigers", "PAC"),
    "pepperdine": ("Pepperdine", "Waves", "PEPP"),
    "portland": ("Portland", "Pilots", "PORT"),
    "saint-marys": ("Saint Mary's", "Gaels", "SMC"),
    "san-diego": ("San Diego", "Toreros", "USD"),
    "san-francisco": ("San Francisco", "Dons", "SF"),
    "santa-clara": ("Santa Clara", "Broncos", "SCU"),
    "seattle": ("Seattle", "Redhawks", "SEA"),
}

CONFS = {
    "AE": ("America East", "AE"),
    "AAC": ("American", "AAC"),
    "ACC": ("ACC", "ACC"),
    "ASUN": ("ASUN", "ASUN"),
    "A10": ("Atlantic 10", "A-10"),
    "BE": ("Big East", "BE"),
    "BSKY": ("Big Sky", "BSky"),
    "BSOU": ("Big South", "BSou"),
    "B10": ("Big Ten", "B1G"),
    "B12": ("Big 12", "B12"),
    "BW": ("Big West", "BW"),
    "CAA": ("CAA", "CAA"),
    "CUSA": ("Conference USA", "C-USA"),
    "HOR": ("Horizon", "Horz"),
    "IVY": ("Ivy League", "Ivy"),
    "MAAC": ("MAAC", "MAAC"),
    "MAC": ("MAC", "MAC"),
    "MEAC": ("MEAC", "MEAC"),
    "MVC": ("Missouri Valley", "MVC"),
    "MW": ("Mountain West", "MW"),
    "NEC": ("NEC", "NEC"),
    "OVC": ("Ohio Valley", "OVC"),
    "PAT": ("Patriot", "Pat"),
    "P12": ("Pac-12", "P12"),
    "SEC": ("SEC", "SEC"),
    "SOC": ("Southern", "SoCon"),
    "SLAND": ("Southland", "SL"),
    "SWAC": ("SWAC", "SWAC"),
    "SUM": ("Summit", "Sum"),
    "SBC": ("Sun Belt", "SBC"),
    "UAC": ("United Athletic", "UAC"),
    "WCC": ("West Coast", "WCC"),
}

# ids currently in teams.ts
import re
raw = Path("/workspace/src/game/teams.ts").read_text()
ids = re.findall(r'\n  \["([^"]+)"', raw)
missing = [i for i in ids if i not in TEAMS]
extra = [i for i in TEAMS if i not in set(ids)]
if missing or extra:
    raise SystemExit(f"id mismatch missing={missing[:20]} extra={extra[:20]} nmiss={len(missing)} nextra={len(extra)}")

pack = {
    "kind": "dribble-2026-names",
    "version": 1,
    "id": "real-schools",
    "title": "Real school names",
    "note": "Fan display pack. Not affiliated with any school, conference, or the NCAA. Default Dribble 2026 ships facsimile names.",
    "teams": {tid: {"name": n, "mascot": m, "abbr": a} for tid, (n, m, a) in TEAMS.items()},
    "conferences": {cid: {"name": n, "short": s} for cid, (n, s) in CONFS.items()},
}

out = Path("/workspace/public/packs/real-schools.json")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(pack, indent=2, ensure_ascii=False) + "\n")
src_copy = Path("/workspace/src/game/packs/real-schools.json")
src_copy.parent.mkdir(parents=True, exist_ok=True)
src_copy.write_text(out.read_text())

csv_path = Path("/workspace/public/packs/real-schools.csv")
csv_lines = ["id,name,mascot,abbr"]
for tid, (n, m, a) in TEAMS.items():
    def cell(v: str) -> str:
        return f'"{v.replace(chr(34), chr(34)+chr(34))}"' if ("," in v or '"' in v) else v
    csv_lines.append(f"{tid},{cell(n)},{cell(m)},{cell(a)}")
csv_path.write_text("\n".join(csv_lines) + "\n")

art = Path("/workspace/artifacts")
art.mkdir(parents=True, exist_ok=True)
(art / "dribble-2026-real-schools.json").write_text(out.read_text())
(art / "dribble-2026-real-schools.csv").write_text(csv_path.read_text())
print(f"wrote {len(pack['teams'])} teams -> {out}")
